version: '3.8'

services:
  mongodb:
    image: bitnami/mongodb:latest
    container_name: mongodb
    environment:
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/bitnami/mongodb

  redis:
    image: bitnami/redis:latest
    container_name: redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/bitnami/redis

  appsmith:
    image: bitnami/appsmith:latest
    container_name: appsmith
    ports:
      - "80:8080"
    environment:
      - APPSMITH_API_HOST=${APPSMITH_API_HOST}
      - APPSMITH_RTS_HOST=${APPSMITH_RTS_HOST}
      - APPSMITH_DATABASE_HOST=${APPSMITH_DATABASE_HOST}
      - APPSMITH_DATABASE_PORT_NUMBER=${APPSMITH_DATABASE_PORT_NUMBER}
      - APPSMITH_DATABASE_USER=${APPSMITH_DATABASE_USER}
      - APPSMITH_DATABASE_NAME=${APPSMITH_DATABASE_NAME}
      - APPSMITH_DATABASE_PASSWORD=${APPSMITH_DATABASE_PASSWORD}
      - APPSMITH_ENCRYPTION_PASSWORD=${APPSMITH_ENCRYPTION_PASSWORD}
      - APPSMITH_ENCRYPTION_SALT=${APPSMITH_ENCRYPTION_SALT}
      - APPSMITH_DATABASE_INIT_DELAY=${APPSMITH_DATABASE_INIT_DELAY}
      - APPSMITH_DATABASE_INIT_DELAY_RTS=${APPSMITH_DATABASE_INIT_DELAY_RTS}
    depends_on:
      - mongodb
      - redis
    volumes:
      - appsmith_data:/bitnami/appsmith

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local
  appsmith_data:
    driver: local

networks:
  default:
    driver: bridge
